name: autofix.ci

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouting repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: 20
          cache: yarn

      - run: yarn
      - run: yarn run lint:fix

      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
