name: Bump package version

permissions:
  contents: write

on:
  push:
    branches:
      - 'master'

jobs:
  bump-package-version:
    timeout-minutes: 4
    runs-on: ubuntu-latest

    steps:
      - name: Checkouting repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: 18
          cache: yarn

      - name: Bump versions
        run: npx changelogithub@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
