name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  test-lint-build:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - name: Checkouting repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: 18
          cache: yarn

      - name: Install deps
        run: yarn install

      - name: Run tests
        run: yarn run test

      - name: Run lint:fix
        run: yarn run lint:fix --ignore-pattern ".github"

      - name: Run Build
        run: yarn run build

      - name: Setup git user
        uses: fregante/setup-git-user@77c1b5542f14ab6db4b8462d6857e31deb988b09
        
      - name: Commit changes
        run: |
          git commit -a -m "chore: apply fixes" || echo "nothing to update"
          git pull
          git push

  bump-package-version:
    needs: test-lint-build
    timeout-minutes: 4
    runs-on: ubuntu-latest

    steps:
      - name: Checkouting repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: 18
          cache: yarn

      - name: Setup git user
        uses: fregante/setup-git-user@77c1b5542f14ab6db4b8462d6857e31deb988b09

      - name: Bump versions
        run: |
          git pull

          npx changelogen@latest --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: git push

  trigger-release:
    needs: [test-lint-build, bump-package-version]
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment
        env:
          TRIGGER_DEPLOYMENT: ${{ secrets.TRIGGER_DEPLOYMENT }}
        shell: bash
        run: curl -X POST $TRIGGER_DEPLOYMENT
