name: Build lint test

on:
  push:
    branches:
      - master

jobs:
  bump-package-version:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkouting repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: 18
          cache: yarn

      - name: Run tests
        run: yarn run test

      - name: Run lint:fix
        run: yarn run lint:fix

      - name: Run Build
        run: yarn run build

      - name: Commit and push if there are changes
        uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore: update deps'
          branch: ${{ github.ref_name }}
          author_name: ${{ github.actor }}
          author_email: noreply@github.com
