name: Auto update dependencies

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  # allow yarn creating lockfile in CI environment
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

jobs:
  auto-update-dependencies:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkouting repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Node setup
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Update package versions
      run: npx taze@latest latest -x '@types/node' -swf

    - name: Update resolution versions
      run: node ./scripts/update-resolution.cjs
      shell: bash

    - name: Update lock file
      run: |
        rm ./yarn.lock
        yarn

    - name: Test if project still builds
      run: yarn build
    
    - name: Commit changes if needed
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "chore: update deps"
        branch: ${{ github.ref_name }}