name: Auto update dependencies

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 3,6'

env:
  # allow yarn creating lockfile in CI environment
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

jobs:
  auto-update-dependencies:
    timeout-minutes: 4
    runs-on: ubuntu-latest

    steps:
      - name: Checkouting repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: 18
          cache: yarn

      - name: Update package versions
        run: npx taze@latest latest -x '@types/node' -swf

      - name: Update resolution versions
        run: node ./scripts/update-resolution.cjs
        shell: bash

      - name: Update lock file
        run: |
          rm ./yarn.lock
          yarn

      - name: Test if project still builds
        run: yarn build

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git commit -am "chore: update deps"
          git push
