name: Auto update go dependencies

on:
  push:
    
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  auto-update-go-dependencies:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Go setup
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Run auto dependency update 
      uses: romoh/dependencies-autoupdate@main
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        # -s - silent, -w - write to package.json -i - install deps
        update-command: "'rm ./yarn.lock && npx taze@latest -swi"
        on-changes-command: "yarn build"