name: Auto update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 3,6'

env:
  # allow yarn creating lockfile in CI environment
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

permissions:
  contents: write

jobs:
  auto-update-dependencies:
    timeout-minutes: 4
    runs-on: ubuntu-latest

    steps:
      - name: Checkouting repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: 18
          cache: yarn

      - name: Update package versions
        run: npx taze@latest latest -x '@types/node' -swf

      - name: Update resolution versions
        run: node ./scripts/update-resolution.cjs
        shell: bash

      - name: Update lock file
        run: |
          rm ./yarn.lock
          yarn

      - name: Test if project still builds
        run: yarn build

      - name: Commit changes
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "${{ github.actor }}"
          git commit -a -m "chore: update deps"

      - name: Push changes
        uses: ad-m/github-push-action@9a2e3c14aaecf56d5816dc3a54514f82050820b2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
