name: Auto update dependencies

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  # allow yarn creating lockfile in CI environment
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

jobs:
  auto-update-dependencies:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkouting repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Node setup
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Run auto dependency update 
      # -s - silent, -w - write to package.json -i - install deps
      run: |
        chmod +x ./scripts/update-deps.sh
        ./scripts/update-deps.sh ${{ secrets.GITHUB_TOKEN }} "rm ./yarn.lock && npx taze@latest -swif" "yarn build"
      shell: bash